import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(BASE_DIR, 'HandsData')

PRINT_TRAIN_DIR = os.path.join(DATA_DIR, 'print-train')
PRINT_TEST_DIR = os.path.join(DATA_DIR, 'print-test')
VEIN_TRAIN_DIR = os.path.join(DATA_DIR, 'vein-train')
VEIN_TEST_DIR = os.path.join(DATA_DIR, 'vein-test')

PRINT_IMAGE_SIZE = (217, 190)
VEIN_IMAGE_SIZE = (180, 180)

NUM_CLASSES = 290
NUM_TRAIN_PER_CLASS = 5
NUM_TEST_PER_CLASS = 5

BATCH_SIZE = 32
NUM_WORKERS = 4
LEARNING_RATE = 1e-4
NUM_EPOCHS = 160
WEIGHT_DECAY = 5e-4

SEED = 42
LABEL_SMOOTHING = 0.1
WARMUP_EPOCHS = 5
EARLY_STOPPING_PATIENCE = 20
EARLY_STOPPING_MIN_DELTA = 0.0

TRAIN_ROTATION_DEGREES = 8
TRAIN_TRANSLATE = 0.05
TRAIN_SCALE_MIN = 0.95
TRAIN_SCALE_MAX = 1.05
TRAIN_BRIGHTNESS = 0.15
TRAIN_CONTRAST = 0.15
TRAIN_RANDOM_ERASE_P = 0.2

FEATURE_DIM = 256
NUM_EXPERTS = 3

SAVE_DIR = os.path.join(BASE_DIR, 'checkpoints')
